//
// small 'test' for c++ mapping classes created by json2class.py generator script
//

#include <sstream>
#include <fstream>
#include <codecvt>

//generated by json2class.py
#include "../out/UserJson.h"

std::string STR(const std::wstring & ws)
{
  return std::string(ws.begin(), ws.end());
}

void testGeneratedMappingClass(const std::string & jsonFileName)
{
  //read json data from file
  std::wifstream wif(jsonFileName);
  wif.imbue(std::locale(std::locale::empty(), new std::codecvt_utf8<wchar_t>));  
  std::wstringstream wss;
  wss << wif.rdbuf();  
  const std::wstring xx = wss.str();

  try
  {
    web::json::value json = web::json::value::parse(xx); //make sure file is in UTF8

    using namespace UserJson;

    //test generated structures
    User u(json);

    bool b = u.get_verified();
    std::cout << "(bool) verified=" << b << std::endl;
    std::cout << std::endl;

    std::cout << "(object) subobj" << std::endl;
    Subobj obj = u.get_subobj();
    std::cout << "\t(int) prop=" << obj.get_prop() << std::endl;
    std::cout << std::endl;

    double d = u.get_weight();
    std::cout << "(double) weight=" << d << std::endl;
    std::cout << std::endl;

    double i = u.get_userid();
    std::cout << "(double) userid=" << i << std::endl;
    std::cout << std::endl;

    std::cout << "(container of object) array" << std::endl;
    const std::vector<ArrrayItem> & arr1 = u.get_arrray();
    for (auto elem : arr1)
      std::cout << "\t(int) elem.prop=" << STR(elem.get_prop()) << std::endl;
    std::cout << std::endl;

    std::cout << "(container of double) items" << std::endl;
    const std::vector<double> & arr2 = u.get_items();
    for (auto elem : arr2)
      std::cout << "\t(double) elem=" << elem << std::endl;
    std::cout << std::endl;

    std::cout << "(container of string) games" << std::endl;
    const std::vector<std::wstring> & arr3 = u.get_games();
    for (auto elem : arr3)
      std::cout << "\t(string) elem=" << STR(elem) << std::endl;
    std::cout << std::endl;

    std::wstring s = u.get_username();
    std::cout << "(string) username=" << STR(s) << std::endl;
    std::cout << std::endl;
  }
  catch (web::json::json_exception & ex)
  {
    std::cout << "Exception: " << ex.what() << std::endl;
  }

  std::cout << "Done" << std::endl;
}


int main(int argc, char* argv[])
{
  //make sure you have previously generated the mapping class for this json file (via json2class.py)
  testGeneratedMappingClass("../user.json");

	return 0;
}

